name: self hosted test

on:
  push:

jobs:
  test:
    runs-on: arc-runner-set
    steps:
      - run: echo "Hello from self-hosted runner"
      - run: uname -a

  hello:
    runs-on: arc-runner-set
    steps:
      - run: echo "Hello from Kubernetes runner"
